// Consolidated multi-report PDF — port of mobile/src/lib/exportPdf.js's
// generateConsolidatedReportPdf. The old app rasterized an off-screen HTML
// table (its only way to get real layout in a browser); the `pdf` package
// has actual table primitives, so this builds the marker x date matrix
// directly as a pw.Table — no off-screen DOM/canvas step needed.
import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'db.dart';
import 'parser_config.dart';

const _accent = PdfColor.fromInt(0xFFE63946);
const _accentSoft = PdfColor.fromInt(0xFFFDECEE);
const _accentDim = PdfColor.fromInt(0xFFB52A35);
const _grey = PdfColor.fromInt(0xFF555555);
const _border = PdfColor.fromInt(0xFFDDDDDD);

class PdfExportService {
  static Future<void> shareConsolidatedReport(int profileId, String? profileName) async {
    final (dates, markers, refRanges) = await Db.instance.getConsolidatedMatrix(profileId);
    final config = ParserConfig.instance;
    final present = markers.keys.toSet();

    final rows = <pw.TableRow>[
      pw.TableRow(
        decoration: const pw.BoxDecoration(color: PdfColors.grey200),
        children: [
          _headerCell('Marker'),
          _headerCell('Range'),
          for (final d in dates) _headerCell(d),
        ],
      ),
    ];

    void appendGroup(String label, List<String> keys) {
      final inGroup = keys.where(present.contains).toList();
      if (inGroup.isEmpty) return;
      rows.add(
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: _accentSoft),
          children: [
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
              child: pw.Text(label.toUpperCase(), style: pw.TextStyle(color: _accentDim, fontWeight: pw.FontWeight.bold, fontSize: 9)),
            ),
            for (var i = 0; i < dates.length + 1; i++) pw.SizedBox(),
          ],
        ),
      );
      for (final canonical in inGroup) {
        final byDate = markers[canonical]!;
        rows.add(
          pw.TableRow(
            children: [
              _cell(canonical),
              _cell(refRanges[canonical] ?? ''),
              for (final d in dates)
                _cell(
                  byDate.containsKey(d) ? _fmt(byDate[d]!) : '—',
                  outOfRange: byDate.containsKey(d) && _isOutOfRange(byDate[d]!, refRanges[canonical]),
                ),
            ],
          ),
        );
      }
    }

    for (final g in config.markerGroups) appendGroup(g.label, g.keys);
    final grouped = config.markerGroups.expand((g) => g.keys).toSet();
    appendGroup('Other', present.difference(grouped).toList()..sort());

    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              children: [
                pw.Text('Track Blood', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: _accent)),
              ],
            ),
            pw.Text(
              'Consolidated Report${profileName != null ? ' — $profileName' : ''}',
              style: pw.TextStyle(fontSize: 12, color: _grey),
            ),
            pw.SizedBox(height: 8),
            pw.Divider(color: _accent, thickness: 2),
            pw.SizedBox(height: 8),
          ],
        ),
        footer: (context) => pw.Padding(
          padding: const pw.EdgeInsets.only(top: 8),
          child: pw.Text(
            'Generated by Track Blood — data stored locally on device, never uploaded.',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
            textAlign: pw.TextAlign.center,
          ),
        ),
        build: (context) => [
          pw.Table(
            border: pw.TableBorder.all(color: _border, width: 0.5),
            columnWidths: {0: const pw.FlexColumnWidth(2.2), 1: const pw.FlexColumnWidth(1.4)},
            children: rows,
          ),
        ],
      ),
    );

    final tempDir = await getTemporaryDirectory();
    final fileName = 'track-blood-report-${DateTime.now().toIso8601String().substring(0, 10)}.pdf';
    final file = File(p.join(tempDir.path, fileName));
    await file.writeAsBytes(await doc.save());

    await SharePlus.instance.share(ShareParams(files: [XFile(file.path)], title: 'My Blood Report — Track Blood'));
  }

  static pw.Widget _headerCell(String text) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
        child: pw.Text(text, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9)),
      );

  static pw.Widget _cell(String text, {bool outOfRange = false}) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
        child: pw.Text(text, style: pw.TextStyle(fontSize: 9, color: outOfRange ? _accentDim : PdfColors.black, fontWeight: outOfRange ? pw.FontWeight.bold : null)),
      );

  static String _fmt(double v) => v == v.roundToDouble() ? v.toStringAsFixed(0) : v.toString();

  static bool _isOutOfRange(double value, String? refRange) {
    final bounds = ParserConfig.parseRefRange(refRange);
    if (bounds == null) return false;
    return (bounds.low != null && value < bounds.low!) || (bounds.high != null && value > bounds.high!);
  }
}
