// ─────────────────────────────────────────────────────────────────────────────
// Consolidated report PDF — renders a branded off-screen HTML table (logo,
// Track Blood colors, out-of-range highlighting) and captures it with
// html2canvas into a paginated jsPDF, the same mechanism the original web
// app's shareAsPDF() uses. A hand-drawn jsPDF table looks bare by comparison —
// real HTML/CSS gets the same visual quality as the web app's export.
// ─────────────────────────────────────────────────────────────────────────────
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';
import { getConsolidatedMatrix } from './db.js';
import { MARKER_GROUPS, parseRefRange } from './parser.js';
import logoUrl from '../assets/logo.png';

function isOutOfRange(value, refRange) {
  const bounds = parseRefRange(refRange);
  if (!bounds) return false;
  return (bounds.low !== null && value < bounds.low) || (bounds.high !== null && value > bounds.high);
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

const STYLE = `
  .pdf-root { font-family: -apple-system, Helvetica, Arial, sans-serif; background: #fff; color: #171717; width: 1000px; padding: 32px; box-sizing: border-box; }
  .pdf-header { display: flex; align-items: center; gap: 16px; margin-bottom: 24px; border-bottom: 3px solid #e63946; padding-bottom: 16px; }
  .pdf-logo { width: 44px; height: auto; }
  .pdf-title { font-size: 22px; font-weight: 800; color: #e63946; }
  .pdf-sub { font-size: 14px; color: #555; margin-top: 2px; }
  .pdf-table { width: 100%; border-collapse: collapse; font-size: 12px; }
  .pdf-table th, .pdf-table td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; white-space: nowrap; }
  .pdf-table thead th { background: #f5f5f5; font-weight: 700; }
  .pdf-table tr.group td { background: #fdecee; color: #b52a35; font-weight: 700; text-transform: uppercase; font-size: 11px; letter-spacing: 0.03em; }
  .pdf-table td.oor { color: #b52a35; font-weight: 700; }
  .pdf-footer { margin-top: 20px; font-size: 10px; color: #999; text-align: center; }
`;

function buildReportHtml(profileName, dates, markers, refRanges) {
  const rowsHtml = [];
  const present = new Set(Object.keys(markers));

  const appendGroup = (label, keys) => {
    const inGroup = keys.filter(k => present.has(k));
    if (!inGroup.length) return;
    rowsHtml.push(`<tr class="group"><td colspan="${2 + dates.length}">${escapeHtml(label)}</td></tr>`);
    for (const canonical of inGroup) {
      const cells = dates.map(d => {
        const v = markers[canonical][d];
        const oor = v !== undefined && isOutOfRange(v, refRanges[canonical]);
        return `<td class="${oor ? 'oor' : ''}">${v !== undefined ? escapeHtml(v) : '—'}</td>`;
      }).join('');
      rowsHtml.push(`<tr><td>${escapeHtml(canonical)}</td><td>${escapeHtml(refRanges[canonical] ?? '')}</td>${cells}</tr>`);
    }
  };

  for (const group of MARKER_GROUPS) appendGroup(group.label, group.keys);
  const grouped = new Set(MARKER_GROUPS.flatMap(g => g.keys));
  appendGroup('Other', [...present].filter(k => !grouped.has(k)));

  return `
    <div class="pdf-root">
      <div class="pdf-header">
        <img src="${logoUrl}" class="pdf-logo" alt="">
        <div>
          <div class="pdf-title">Track Blood</div>
          <div class="pdf-sub">Consolidated Report${profileName ? ' — ' + escapeHtml(profileName) : ''}</div>
        </div>
      </div>
      <table class="pdf-table">
        <thead><tr><th>Marker</th><th>Range</th>${dates.map(d => `<th>${escapeHtml(d)}</th>`).join('')}</tr></thead>
        <tbody>${rowsHtml.join('')}</tbody>
      </table>
      <div class="pdf-footer">Generated by Track Blood — data stored locally on device, never uploaded.</div>
    </div>
  `;
}

export async function generateConsolidatedReportPdf(profileId, profileName) {
  const { dates, markers, refRanges } = await getConsolidatedMatrix(profileId);

  const container = document.createElement('div');
  container.style.position = 'fixed';
  container.style.top = '-99999px';
  container.style.left = '0';
  container.innerHTML = `<style>${STYLE}</style>${buildReportHtml(profileName, dates, markers, refRanges)}`;
  document.body.appendChild(container);

  try {
    const root = container.querySelector('.pdf-root');
    const canvas = await html2canvas(root, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
    const imgData = canvas.toDataURL('image/jpeg', 0.92);

    const pdf = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
    const pageW = pdf.internal.pageSize.getWidth();
    const pageH = pdf.internal.pageSize.getHeight();
    const imgW = pageW;
    const imgH = canvas.height * (pageW / canvas.width);
    let remaining = imgH;
    let offset = 0;
    while (remaining > 0) {
      pdf.addImage(imgData, 'JPEG', 0, offset, imgW, imgH);
      remaining -= pageH;
      if (remaining > 0) { pdf.addPage(); offset -= pageH; }
    }

    const arrayBuffer = pdf.output('arraybuffer');
    const base64 = arrayBufferToBase64(arrayBuffer);
    const fileName = `track-blood-report-${new Date().toISOString().slice(0, 10)}.pdf`;
    const path = `shared/${fileName}`;
    await Filesystem.writeFile({ path, data: base64, directory: Directory.Cache, recursive: true });
    const { uri } = await Filesystem.getUri({ path, directory: Directory.Cache });

    await Share.share({ title: 'My Blood Report — Track Blood', url: uri });
    return uri;
  } finally {
    document.body.removeChild(container);
  }
}

function arrayBufferToBase64(buffer) {
  let binary = '';
  const bytes = new Uint8Array(buffer);
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}
